[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.20"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-net = "0.2" # HTTP istekleri için

[lib]
crate-type = ["cdylib"]
