# version: '3.8'
# services:
#   rust-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - mutagen:/usr/src/app:cached
#     ports:
#       - '8000:8000'
#     command: cargo watch -x run

version: '3.9'

services:
  app:
    build: .
    container_name: 'cargo-watch-example'
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: sh -c "cargo watch -x run"
